<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width,initial-scale=1'>

	<!-- Primary Meta Tags -->
	<title>Dawid Huczyński</title>
	<meta name="title" content="Dawid Huczyński">
	<meta name="description" content="">

	<!-- Open Graph / Facebook -->
	<meta property="og:type" content="website">
	<meta property="og:url" content="https://dawid.huczynski.pl/">
	<meta property="og:title" content="Dawid Huczyński">
	<meta property="og:description" content="">
	<meta property="og:image" content="https://dawid.huczynski.pl/images/wh-social.jpg">

	<!-- Twitter -->
	<meta property="twitter:card" content="summary_large_image">
	<meta property="twitter:url" content="https://dawid.huczynski.pl/">
	<meta property="twitter:title" content="Dawid Huczyński">
	<meta property="twitter:description" content="">
	<meta property="twitter:image" content="https://dawid.huczynski.pl/images/wh-social.jpg">

	<!-- Optional Additions for Consideration -->
	<meta property="og:site_name" content="Dawid Huczyński">

	<!-- <link rel="icon" href="../images/favicon.ico" sizes="any"> -->
	<link rel="icon" href="../svg/logo-dh.svg" type="image/svg+xml">
	<!-- <link rel="apple-touch-icon" href="../images/apple-touch-icon.png"> -->
	<link rel="manifest" href="../theme/manifest.webmanifest">
	<meta name="theme-color" content="#92ac41" />
	<!-- <link rel="preconnect" href="https://fonts.googleapis.com"> -->
	<!-- <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> -->
	<!-- <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500&display=swap" rel="stylesheet">  -->
	<!-- <link rel="stylesheet" href="leaflet.css" data-svelte="svelte-f6hidj"> -->


	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet">
	<!-- <link href="../theme/css/prism-material-light.css" rel="stylesheet" /> -->
	<link href="../theme/css/prism-gruvbox-dark.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="../theme/css/global.css" media="screen">

	<meta http-equiv="content-security-policy" content="">
		<link href="../_app/immutable/assets/_page-37769e9d.css" rel="stylesheet">
		<link href="../_app/immutable/assets/Nav-4ff2e076.css" rel="stylesheet">
		<link rel="modulepreload" href="../_app/immutable/start-de44d3c8.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/index-5cf732b6.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/singletons-ca1e47c6.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/preload-helper-41c905a7.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/control-f5b05b5f.js">
		<link rel="modulepreload" href="../_app/immutable/components/layout.svelte-958a1762.js">
		<link rel="modulepreload" href="../_app/immutable/modules/pages/_layout.js-eb00e147.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/index-dc735eee.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/_layout-cbc6a3fd.js">
		<link rel="modulepreload" href="../_app/immutable/components/pages/lectures/_slug_/_page.svelte-688eb02c.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/Nav-cd4a338e.js">
		<link rel="modulepreload" href="../_app/immutable/modules/pages/lectures/_slug_/_page.js-72c88d67.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/dynamic-import-helper-be004503.js">
		<link rel="modulepreload" href="../_app/immutable/chunks/_page-c455a45e.js">

	<!-- Statistics -->
	<!-- Umami -->
	<script async defer data-website-id="55055229-61bf-4885-99a6-985a9a75049b"
		src="https://stats.huczynski.pl/umami.js"></script>
	<!-- Plausible -->
	<script defer data-domain="dawid.huczynski.pl" src="https://stats2.huczynski.pl/js/script.js"></script>
	<!-- Matomo -->
	<script>
		var _paq = window._paq = window._paq || [];
		/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
		_paq.push(['trackPageView']);
		_paq.push(['enableLinkTracking']);
		(function () {
			var u = "//matomo.huczynski.pl/";
			_paq.push(['setTrackerUrl', u + 'matomo.php']);
			_paq.push(['setSiteId', '1']);
			var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
			g.async = true; g.src = u + 'matomo.js'; s.parentNode.insertBefore(g, s);
		})();
	</script>
	<!-- End Matomo Code -->

</head>

<body>
	<div>


<nav id="nav" class="svelte-jld698 top"><ul class="svelte-jld698"><li class="svelte-jld698"><a href="/#start" class="nav-link logo active svelte-jld698"><img alt="Logo" src="/svg/logo-dh.svg" class="svelte-jld698"></a></li>
		<li class="svelte-jld698"><a href="/#portfolio" class="nav-link svelte-jld698"><!-- HTML_TAG_START --><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10.59 4.59C10.21 4.21 9.7 4 9.17 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-1.41-1.41z" /></svg><!-- HTML_TAG_END --></a></li>
		<li class="svelte-jld698"><a href="/#about" class="nav-link svelte-jld698"><!-- HTML_TAG_START --><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v1c0 .55.45 1 1 1h14c.55 0 1-.45 1-1v-1c0-2.66-5.33-4-8-4z" /></svg><!-- HTML_TAG_END --></a></li>
		<li class="svelte-jld698"><a href="/#contact" class="nav-link svelte-jld698"><!-- HTML_TAG_START --><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-.4 4.25l-7.07 4.42c-.32.2-.74.2-1.06 0L4.4 8.25c-.25-.16-.4-.43-.4-.72 0-.67.73-1.07 1.3-.72L12 11l6.7-4.19c.57-.35 1.3.05 1.3.72 0 .29-.15.56-.4.72z" /></svg><!-- HTML_TAG_END --></a></li>
		<li class="svelte-jld698"><a href="/blog" class="nav-link svelte-jld698"><!-- HTML_TAG_START --><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m20.39 7.1023-3.4925-3.4925 1.146-1.146c0.30923-0.30923 0.69122-0.46385 1.146-0.46385 0.45475 0 0.83674 0.15462 1.146 0.46385l1.2005 1.2005c0.30923 0.30923 0.46385 0.69122 0.46385 1.146 0 0.45475-0.15462 0.83674-0.46385 1.146zm-1.146 1.146-13.752 13.752h-3.4925v-3.4925l13.752-13.752z" /></svg><!-- HTML_TAG_END --></a></li></ul>
	<div class="submenu svelte-jld698 title"><a href="" class="tt svelte-jld698">revit api</a></div>
</nav>
<main class="prezentacja"><section id="0" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h1 id="wprowadzenie-do-api-revita">Wprowadzenie do API Revita</h1>
<h2 id="dawidhuczynskipllecturesrevit-api"><a href="https://dawid.huczynski.pl/lectures/revit-api">dawid.huczynski.pl/lectures/revit-api</a></h2>
<h3 id="dawidhuczynskigmailcom"><a href="mailto:dawid.huczynski@gmail.com">dawid.huczynski@gmail.com</a></h3>
<!-- HTML_TAG_END --></section><section id="1" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h1 id="spotkanie-1">Spotkanie 1.</h1>
<!-- HTML_TAG_END --></section><section id="2" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="narzędzia-i-ustawianie-środowiska">Narzędzia i ustawianie środowiska</h2>
<ul>
<li><strong>Pyrevit</strong> - addon do tworzenia własnych dodatków oraz mały kombajn z narzędziami: <br>
  <a href="https://github.com/eirannejad/pyRevit/releases">https://github.com/eirannejad/pyRevit/releases</a> <br></li>
<li><strong>RevitPythonShell</strong> - interaktywna konsola Pythona w Revicie: <br>
  <a href="https://github.com/architecture-building-systems/revitpythonshell/releases">https://github.com/architecture-building-systems/revitpythonshell/releases</a></li>
<li><strong>stubs</strong> - narzędzie do autouzupełniania Revitowych komend w VS Code: <br>
  <a href="https://www.macro4bim.com/post/create-python-stubs">https://www.macro4bim.com/post/create-python-stubs</a> <br>
  <a href="https://github.com/gtalarico/ironpython-stubs">https://github.com/gtalarico/ironpython-stubs</a> <br></li>
<li><strong>RevitLookup</strong> - narzędzie do podglądania parametrów obiektów Revicie: <br>
  <a href="https://github.com/jeremytammik/RevitLookup">https://github.com/jeremytammik/RevitLookup</a></li>
<li><strong>git</strong> - program do wersjonowania kodu i pracy w zespole, kombajn: <br>
  <a href="https://git-scm.com/">https://git-scm.com/</a></li>
</ul>
<!-- HTML_TAG_END --></section><section id="3" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="miejsca-do-szukania-wiedzy">Miejsca do szukania wiedzy:</h2>
<ul>
<li><a href="https://www.revitapidocs.com/">https://www.revitapidocs.com/</a></li>
<li><a href="https://apidocs.co/apps/revit/2021/">https://apidocs.co/apps/revit/2021/</a></li>
<li><a href="https://help.autodesk.com/view/RVT/2022/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">https://help.autodesk.com/view/RVT/2022/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html</a></li>
<li><a href="https://thebuildingcoder.typepad.com/">https://thebuildingcoder.typepad.com/</a></li>
<li><a href="http://wiki.theprovingground.org/revit-api">http://wiki.theprovingground.org/revit-api</a></li>
<li><a href="https://dynamopythonprimer.gitbook.io/">https://dynamopythonprimer.gitbook.io/</a></li>
<li><a href="https://www.youtube.com/channel/UC1Dx-jGyRbvvHzZ8ZyGWF5w/playlists">https://www.youtube.com/channel/UC1Dx-jGyRbvvHzZ8ZyGWF5w/playlists</a></li>
<li><a href="https://github.com/gtalarico/python-revit-resources">https://github.com/gtalarico/python-revit-resources</a></li>
<li><a href="https://github.com/architecture-building-systems/revitpythonshell">https://github.com/architecture-building-systems/revitpythonshell</a></li>
<li><a href="https://github.com/Amoursol/dynamoPython">https://github.com/Amoursol/dynamoPython</a></li>
<li><a href="https://daren-thomas.gitbooks.io/scripting-autodesk-revit-with-revitpythonshell/content/">https://daren-thomas.gitbooks.io/scripting-autodesk-revit-with-revitpythonshell/content/</a></li>
</ul>
<!-- HTML_TAG_END --></section><section id="4" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="sposób-czytania-skryptów">Sposób czytania skryptów</h2>
<ul>
<li><code>#! python3</code> - definiuje jakiego języka używa skrypt</li>
<li><code># -*- coding: utf-8 -*-</code> - definuje zakres znaków unicode UTF-8 (tu też są polskie znaki)</li>
</ul>
<pre class="language-python"><code class="language-python">#! python3
# -*- coding: utf-8 -*-
import xyz
import abc
from foo import bar

CONSTANT_X = 1
CONSTANT_Y = False
CONSTANT_Z = None

def something(a,b,c):
    return a,b,c

def main():
    return something(a,b,c)

if __name__ == &quot;__main__&quot;:
    main()
</code></pre>
<!-- HTML_TAG_END --></section><section id="5" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pipenv">pipenv</h2>
<pre><code class="language-bash">pip install --user pipenv
pipenv install requests
pipenv run python main.py
pipenv shell

</code></pre>
<!-- HTML_TAG_END --></section><section id="6" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="używanie-bibliotek-pythona">Używanie bibliotek pythona</h2>
<pre class="language-python"><code class="language-python">import sys
sys.path.append(&#39;sciezka/do/modulow&#39;)

</code></pre>
<!-- HTML_TAG_END --></section><section id="7" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="api-a-wersje-pythona">API a wersje pythona</h2>
<ul>
<li>API Dynamo - zależnie od wersji Dynamo IronPython 2.7 / python 3.8</li>
<li>API RPSHELL (Python) - IronPython 2.7 / python 3.8</li>
<li>API Macros - IronPython 2.7</li>
</ul>
<!-- HTML_TAG_END --></section><section id="8" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="język-statyczny-i-dynamiczny">Język statyczny i dynamiczny</h2>
<p>Types - typy (int, float, str, Object, Enum, Element, Id):</p>
<ul>
<li>static types</li>
<li>dynamic types</li>
</ul>
<!-- HTML_TAG_END --></section><section id="9" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="podstawy-api">Podstawy API</h2>
<p>Kod do skopiowania do skryptów Dynamo. NIE KOPIUJCIE TEGO, serio! :D<br>
słowo klucz: &quot;Maintnance&quot;</p>
<pre class="language-python"><code class="language-python">import clr # .NET&#39;s Common Language Runtime.

# Dodawanie modulow.
import sys
sys.path.append(&#39;C:\Program Files (x86)\IronPython 2.7\Lib&#39;)

# Dodawanie standarowych typow
import System
from System import Array
from System.Collections.Generic import *

# Dodawanie standarowych typow Dynamo
clr.AddReference(&#39;ProtoGeometry&#39;)
from Autodesk.DesignScript.Geometry import *

# Dodawanie standardowych typow Dynamo-Revit
clr.AddReference(&quot;RevitNodes&quot;)
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

# Dodanie TransactionManagera i DocumentManagera
clr.AddReference(&quot;RevitServices&quot;)
import RevitServices
from RevitServices.Persistence import DocumentManager 
from RevitServices.Transactions import TransactionManager 

# Dodawanie API Revita
clr.AddReference(&quot;RevitAPI&quot;)
clr.AddReference(&quot;RevitAPIUI&quot;)

import Autodesk 
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication 
app = uiapp.Application 
uidoc = uiapp.ActiveUIDocument

</code></pre>
<!-- HTML_TAG_END --></section><section id="10" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="co-ma-skarpetka-wspólnego-z-revitem">Co ma skarpetka wspólnego z Revitem?</h2>
<p>jednostki</p>
<pre class="language-python"><code class="language-python">def feet_to_meter(feet):
    return feet * 0.3048


def meter_to_feet(meter):
    return meter / 0.3048


def sqr_feet_to_meter(sqrfeet):
    return sqrfeet * 0.09290304


def sqr_meter_to_feet(sqrmeter):
    return sqrmeter / 0.09290304


</code></pre>
<!-- HTML_TAG_END --></section><section id="11" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="inny-sposób-na-jednostki">Inny sposób na jednostki</h2>
<pre class="language-python"><code class="language-python">detail_line = UnwrapElement(IN[0])
decimal_feet_length = detail_line.GeometryCurve.Length
metric_length = UnitUtils.Convert(
    decimal_feet_length, 
    DisplayUnitType.DUT_DECIMAL_FEET, 
    DisplayUnitType.DUT_MILLIMETERS)
OUT = metric_length

</code></pre>
<!-- HTML_TAG_END --></section><section id="12" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="struktura-api-i-przeszukiwanie">Struktura API i przeszukiwanie</h2>
<pre class="language-python"><code class="language-python">import os
import types

def walker(lib, name, relations=None, limit=2):
    relations = [[&quot;&quot;, name, lib.__doc__]] if relations is None else relations
    IGNORE = [str, int, float, complex, list, tuple, range, dict, bool, bytes]
    if limit == 0:
        return relations
    else:
        limit -= 1
    for x in dir(lib):
        if not x.startswith(&quot;_&quot;):
            try:
                a = getattr(lib, x)
                if type(a) not in IGNORE and name not in [&quot;OSError&quot;, &quot;Error&quot;]:
                    el = [name, f&quot;{name}.{x}&quot;, a.__doc__]
                    if el not in relations:
                        relations.append(el)
                        relations = walker(a, f&quot;{name}.{x}&quot;, relations, limit=limit)
            except:
                pass
    return relations

##############################################################
import plotly.graph_objects as go
import plotly

relations = walker(plotly, &quot;plotly&quot;)
parents, labels, helps = zip(*relations)

fig = go.Figure(
    go.Treemap(
        labels=labels,
        parents=parents,
        # values = helps,
    )
)

fig.update_layout(margin=dict(t=50, l=25, r=25, b=25))
plotly.offline.plot(fig, filename=&quot;./index.html&quot;)
fig.show()

</code></pre>
<!-- HTML_TAG_END --></section><section id="13" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="podstawowe-klasy">Podstawowe klasy</h2>
<h2 id="element">Element.*</h2>
<div class='trzy-kolumny'>
<p>
ArePhasesModifiable<br>
AssemblyInstanceId<br>
<strong>BoundingBox</strong><br>
CanBeHidden<br>
CanBeLocked<br>
CanDeleteSubelement<br>
CanHaveAnalyticalModel<br>
CanHaveTypeAssigned<br>
<strong>Category</strong><br>
<strong>ChangeTypeId</strong><br>
CreatedPhaseId<br>
DeleteEntity<br>
DeleteSubelement<br>
DeleteSubelements<br>
DemolishedPhaseId<br>
DesignOption<br>
Dispose<br>
Document<br>
Equals<br>
<strong>Geometry</strong><br>
GetAnalyticalModel<br>
GetAnalyticalModelId<br>
GetChangeTypeAny<br>
GetChangeTypeElementAddition<br>
GetChangeTypeElementDeletion<br>
GetChangeTypeGeometry<br>
GetChangeTypeParameter<br>
</p>
<p>
GetDependentElements<br>
GetEntity<br>
GetEntitySchemaGuids<br>
GetExternalFileReference<br>
GetExternalResourceReference<br>
GetExternalResourceReferences<br>
GetGeneratingElementIds<br>
GetGeometryObjectFromReference<br>
GetHashCode<br>
GetMaterialArea<br>
GetMaterialIds<br>
GetMaterialVolume<br>
GetMonitoredLinkElementIds<br>
GetMonitoredLocalElementIds<br>
GetOrderedParameters<br>
GetParameterFormatOptions<br>
GetParameters<br>
GetPhaseStatus<br>
GetSubelements<br>
GetType<br>
<strong>GetTypeId</strong><br>
GetValidTypes<br>
GroupId<br>
HasPhases<br>
<strong>Id</strong><br>
IsExternalFileReference<br>
IsHidden<br>
</p>
<p>
IsMonitoringLinkElement<br>
IsMonitoringLocalElement<br>
IsPhaseCreatedValid<br>
IsPhaseDemolishedValid<br>
IsTransient<br>
IsValidObject<br>
IsValidType<br>
<strong>LevelId</strong><br>
<strong>Location</strong><br>
<strong>LookupParameter</strong><br>
MemberwiseClone<br>
<strong>Name</strong><br>
OwnerViewId<br>
Parameter<br>
Parameters<br>
<strong>ParametersMap</strong><br>
Pinned<br>
ReferenceEquals<br>
RefersToExternalResourceReference<br>
RefersToExternalResourceReferences<br>
ReleaseUnmanagedResources<br>
SetEntity<br>
ToString<br>
UniqueId<br>
VersionGuid<br>
ViewSpecific<br>
WorksetId<br>
getBoundingBox<br>
setElementType<br>
</p>
</div>



<!-- HTML_TAG_END --></section><section id="14" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="podstawowe-klasy">Podstawowe klasy</h2>
<h2 id="wall">Wall.*</h2>
<div class='trzy-kolumny'>
<p>
ArePhasesModifiable<br>
AssemblyInstanceId<br>
<strong>BoundingBox</strong><br>
CanBeHidden<br>
CanBeLocked<br>
CanDeleteSubelement<br>
CanHaveAnalyticalModel<br>
CanHaveTypeAssigned<br>
<strong>Category</strong><br>
<strong>ChangeTypeId</strong><br>
<strong>Create</strong><br>
CreatedPhaseId<br>
CurtainGrid<br>
DeleteEntity<br>
DeleteSubelement<br>
DeleteSubelements<br>
DemolishedPhaseId<br>
DesignOption<br>
Dispose<br>
Document<br>
Equals<br>
FindInserts<br>
Flip<br>
Flipped<br>
<strong>Geometry</strong><br>
GetAnalyticalModel<br>
GetAnalyticalModelId<br>
GetChangeTypeAny<br>
GetChangeTypeElementAddition<br>
GetChangeTypeElementDeletion<br>
GetChangeTypeGeometry<br>
GetChangeTypeParameter<br>
</p>
<p>
<strong>GetDependentElements</strong><br>
GetEntity<br>
GetEntitySchemaGuids<br>
GetExternalFileReference<br>
GetExternalResourceReference<br>
GetExternalResourceReferences<br>
<strong>GetGeneratingElementIds</strong><br>
GetGeometryObjectFromReference<br>
GetHashCode<br>
GetMaterialArea<br>
GetMaterialIds<br>
GetMaterialVolume<br>
GetMonitoredLinkElementIds<br>
GetMonitoredLocalElementIds<br>
GetOrderedParameters<br>
GetParameterFormatOptions<br>
GetParameters<br>
GetPhaseStatus<br>
GetStackedWallMemberIds<br>
GetSubelements<br>
GetType<br>
<strong>GetTypeId</strong><br>
GetValidTypes<br>
GroupId<br>
HasPhases<br>
<strong>Id</strong><br>
IsExternalFileReference<br>
IsHidden<br>
IsMonitoringLinkElement<br>
IsMonitoringLocalElement<br>
IsPhaseCreatedValid<br>
IsPhaseDemolishedValid<br>
</p>
<p>
IsStackedWall<br>
IsStackedWallMember<br>
IsTransient<br>
IsValidObject<br>
IsValidType<br>
<strong>LevelId</strong><br>
<strong>Location</strong><br>
<strong>LookupParameter</strong><br>
MemberwiseClone<br>
<strong>Name</strong><br>
<strong>Orientation</strong><br>
OwnerViewId<br>
Parameter<br>
Parameters<br>
<strong>ParametersMap</strong><br>
Pinned<br>
ReferenceEquals<br>
RefersToExternalResourceReference<br>
RefersToExternalResourceReferences<br>
ReleaseUnmanagedResources<br>
<strong>SetEntity</strong><br>
StackedWallOwnerId<br>
StructuralUsage<br>
ToString<br>
UniqueId<br>
VersionGuid<br>
ViewSpecific<br>
<strong>WallType</strong><br>
<strong>Width</strong><br>
WorksetId<br>
getBoundingBox<br>
setElementType<br>
</p>
</div>



<!-- HTML_TAG_END --></section><section id="15" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<ul>
<li>możliwości</li>
<li>tworzenie interfejsu do skryptu</li>
<li>ustawianie addinów pod firmę (pipeline developera)</li>
</ul>
<!-- HTML_TAG_END --></section><section id="16" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-tab.png" alt="pyrevit-tab"></p>
<ol>
<li>Tab coloring - koloruje wam zakładki wg otwartych projektów i rodzin. Minify revit UI - chowa wam górne zakładki których nie używacie np mi zostawia tylko Architecture, Annotate i Modify ( ustawia się to klikając na ikonkę s SHIFTEM)</li>
<li>Sync Views - synchronizuje widoki np jak zmieniasz często rzuty (np. sprawdzając szachty) to mając włączoną tą opcję zawsze widok ląduje w tym samym miejscu co na poprzednim rzucie (resetuje się np w momencie wejścia na widok 3d)</li>
<li>Zaawansowane zaznaczanie - działa jak Pamięć w kalkulatorze: zaznaczasz parę obiektów dodajesz do pamięci, zaznaczasz inne dodajesz do pamięci. potem jak klikniesz MRead to zaznaczone zostaną wszystkie poprzednio zaznaczone elementy</li>
<li>Make Pattern - szybko możesz tworzyć szrafurę np trawy, kostki, wzór płytek itp.</li>
<li>Sheets - dla mnie najwygodniejsze jest kopiowanie legend na inne rysunki (PB, PW - na jednym rysunku ustawiasz powtarzające się legendy a potem kopiujesz je na wszystkie inne rysunki i wklejają się w tym samym miejscu) Druga to Batch Sheet Maker - na szybko generuje dużo rysunków wpisujesz tylko nr rysunku [tab] nazewa rysunku i masz rysunek ( ja do PW mam w pliku tekstowym zestaw rysunków które przeklejam do tego narzędzia na etapie PW i od razu mam przygotowane puste rysunki z numerami i nazwami.</li>
<li>Duzo ułatwien w tym miejscu, najfajniejsze to chyba Kopiowanie view templates do innych otwartych plików.</li>
<li>Preflight Checks - moje ulubione narzędzie pokazuje w ładnej graficznej formie &quot;kondycję&quot; twojego revitowego pliku i co może być do poprawy.</li>
<li>Team - ważna rzecz do sprawdzania: Who did that? kto stworzył elementi kto ostatni go edytował.</li>
<li>Czyszczenie rzeczy które czasami jest zbyt dobre, ale przynajmniej potrafi wyczyścić elementy których nie czyści purge.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="17" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-sheets.png" alt="pyrevit-sheets"></p>
<ol start="5">
<li>Sheets - dla mnie najwygodniejsze jest kopiowanie legend na inne rysunki (PB, PW - na jednym rysunku ustawiasz powtarzające się legendy a potem kopiujesz je na wszystkie inne rysunki i wklejają się w tym samym miejscu) Druga to Batch Sheet Maker - na szybko generuje dużo rysunków wpisujesz tylko nr rysunku [tab] nazewa rysunku i masz rysunek ( ja do PW mam w pliku tekstowym zestaw rysunków które przeklejam do tego narzędzia na etapie PW i od razu mam przygotowane puste rysunki z numerami i nazwami.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="18" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-views.png" alt="pyrevit-views"></p>
<ol start="6">
<li>Duzo ułatwien w tym miejscu, najfajniejsze to chyba Kopiowanie view templates do innych otwartych plików.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="19" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-checks1.png" alt="pyrevit-checks1"></p>
<ol start="7">
<li>Preflight Checks - moje ulubione narzędzie pokazuje w ładnej graficznej formie &quot;kondycję&quot; twojego revitowego pliku i co może być do poprawy.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="20" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-checks2.png" alt="pyrevit-checks2"></p>
<ol start="7">
<li>Preflight Checks - moje ulubione narzędzie pokazuje w ładnej graficznej formie &quot;kondycję&quot; twojego revitowego pliku i co może być do poprawy.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="21" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-checks3.png" alt="pyrevit-checks3"></p>
<ol start="7">
<li>Preflight Checks - moje ulubione narzędzie pokazuje w ładnej graficznej formie &quot;kondycję&quot; twojego revitowego pliku i co może być do poprawy.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="22" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-checks4.png" alt="pyrevit-checks4"></p>
<ol start="7">
<li>Preflight Checks - moje ulubione narzędzie pokazuje w ładnej graficznej formie &quot;kondycję&quot; twojego revitowego pliku i co może być do poprawy.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="23" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pyrevit">Pyrevit</h2>
<p><img src="/images/lectures/pyrevit-who.png" alt="pyrevit-who"></p>
<ol start="8">
<li>Team - ważna rzecz do sprawdzania: Who did that? kto stworzył elementi kto ostatni go edytował.</li>
</ol>
<!-- HTML_TAG_END --></section><section id="24" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h1 id="spotkanie-2">Spotkanie 2.</h1>
<!-- HTML_TAG_END --></section><section id="25" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="klasy">Klasy</h2>
<p>Czym są klasy i ich dziedziczenie</p>
<pre class="language-python"><code class="language-python">class Osoba():
    def __init__(self, wiek, wysokosc):
        self.wiek = wiek
        self.wysoksc = wysokosc
        self.smierc = None
        self.martwy = False

    def umarl(self):
        self.smierc = self.wiek
        self.martwy = True


class Kobieta(Osoba):
    def __init__(self, wiek, wysokosc):
        super().__init__(wiek, wysokosc)
        self.dzieci = None
        self.ulubione_ksiazki = []


class Pilotka(Kobieta):
    def __init__(self, wiek, wysokosc, doswiadczenie):
        super().__init__(wiek, wysokosc)
        self.doswiadczenie = doswiadczenie
        self.w_powietrzu = False
    
    def startuje():
        self.w_powietrzu = True

</code></pre>
<!-- HTML_TAG_END --></section><section id="26" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="pomocne-biblioteki-pythona">Pomocne biblioteki Pythona</h2>
<ul>
<li>math</li>
<li>itertools</li>
<li>collections.namedtuple</li>
<li>pandas</li>
<li>numpy</li>
<li>bokeh / plotly</li>
<li>pillow</li>
<li>k3d</li>
</ul>
<!-- HTML_TAG_END --></section><section id="27" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="dynamo">Dynamo</h2>
<ul>
<li>UnwrapElement</li>
<li>Transaction a TransactionGroup a TransactionManager</li>
<li>uidoc.Selection</li>
<li>próba wyjaśnienia różnic (importowane biblioteki).</li>
</ul>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitAPI&quot;)
Autodesk.Revit.DB.Level

clr.AddReference(&quot;RevitNodes&quot;)
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
Revit.Elements.Level

</code></pre>
<!-- HTML_TAG_END --></section><section id="28" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="dynamo-in-out">Dynamo IN-OUT</h2>
<pre class="language-python"><code class="language-python">input_list_of_numbers = IN[0] #Here we take an input
output_list_of_numbers = [] #We create an empty list to output

for number in input_list_of_numbers: #Looping through input
    new_number = number + 1 #Adding 1 to each number
    output_list_of_numbers.append(new_number)

OUT = output_list_of_numbers #Here we output the new &#39;+1&#39; list

</code></pre>
<!-- HTML_TAG_END --></section><section id="29" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="revit-python-shell">Revit Python Shell</h2>
<p>Interaktywna zabawa</p>
<!-- HTML_TAG_END --></section><section id="30" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="filteredelementcollector">FilteredElementCollector</h2>
<pre class="language-python"><code class="language-python">collector = FilteredElementCollector(doc)

# Kategoria
meble_collector = collector.OfCategory(BuiltInCategory.OST_Furniture)

# Klasa
sciany_collector = collector.OfClass(Wall)

# typ czy rzeczywisty obiekt
typy_scian = sciany_collector.WhereElementIsNotElementType()
sciany_iterator = sciany_collector.WhereElementIsElementType()

# zamiana z zapytania na listę obiektów
sciany = sciany_iterator.ToElements()

# przykłądowy jednolinijkowiec
meble = (FilteredElementCollector(doc)
                 .OfCategory(BuiltInCategory.OST_Furniture)
                 .WhereElementIsNotElementType()
                 .ToElements()
                 )

OUT = meble

</code></pre>
<!-- HTML_TAG_END --></section><section id="31" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="uidocselection">uidoc.Selection</h2>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitAPI&quot;)

from Autodesk.Revit.DB import (
    ElementId,
)

clr.AddReference(&quot;System&quot;)
from System.Collections.Generic import List

uidoc = __revit__.ActiveUIDocument  # type: ignore
doc = __revit__.ActiveUIDocument.Document  # type: ignore


def select(elements, by_id=False, uidoc=uidoc):
    &quot;&quot;&quot;select elements in view&quot;&quot;&quot;
    elements_by_id = []
    if not by_id:
        for el in elements:
            elements_by_id.append(el.Id)
    else:
        elements_by_id = elements
    Icollection = List[ElementId](elements_by_id)
    uidoc.Selection.SetElementIds(Icollection)
</code></pre>
<!-- HTML_TAG_END --></section><section id="32" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h3 id="filtrowanie--zaznaczanie">Filtrowanie + zaznaczanie</h3>
<p>Skrypt do wybierania elementów i zanzaczania ich w modelu</p>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitAPI&quot;)

from Autodesk.Revit.DB import (
    ElementId,
    FilteredElementCollector,
    BuiltInCategory,
)

clr.AddReference(&quot;System&quot;)
from System.Collections.Generic import List

# Dodanie TransactionManagera i DocumentManagera
clr.AddReference(&quot;RevitServices&quot;)
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

def select(elements, by_id=False, uidoc=uidoc):
    &quot;&quot;&quot;select elements in view&quot;&quot;&quot;
    elements_by_id = []
    if not by_id:
        for el in elements:
            elements_by_id.append(el.Id)
    else:
        elements_by_id = elements
    Icollection = List[ElementId](elements_by_id)
    uidoc.Selection.SetElementIds(Icollection)

# przykłądowy jednolinijkowiec
walls = ( FilteredElementCollector(doc)
            .OfCategory(BuiltInCategory.OST_Walls)
            .WhereElementIsNotElementType()
            .ToElements()
)

wybrane = []
for wall in walls:
    if &quot;gk&quot; in wall.Category.Name.lower():
        wybrane.append(wall)

select(wybrane)

</code></pre>
<!-- HTML_TAG_END --></section><section id="33" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h1 id="spotkanie-3">Spotkanie 3.</h1>
<!-- HTML_TAG_END --></section><section id="34" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="transaction">Transaction</h2>
<p>Jak działa wprowadzanie zmian w modelu. Są trzy typy transakcji:</p>
<ul>
<li>Transaction </li>
<li>TransactionGroup</li>
<li>TransactionManager - Dynamo</li>
</ul>
<!-- HTML_TAG_END --></section><section id="35" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="transactionmanager---dynamo">TransactionManager - Dynamo</h2>
<pre class="language-python"><code class="language-python">TransactionManager.Instance.EnsureInTransaction(doc)
zrob_cos()
TransactionManager.Instance.TransactionTaskDone()

</code></pre>
<!-- HTML_TAG_END --></section><section id="36" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="transaction">Transaction</h2>
<pre class="language-python"><code class="language-python">t = Transaction(doc, &#39;Opis&#39;)
t.Start()
try:
    zrob_cos()
except:
    t.RollBack()
else:
    t.Commit()

</code></pre>
<!-- HTML_TAG_END --></section><section id="37" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="transactiongroup">TransactionGroup</h2>
<pre class="language-python"><code class="language-python">tg = TransactionGroup(doc, &quot;\{\} number assing&quot;.format(el_type))
tg.Start()

t = Transaction(doc, &quot;Zmiana 1&quot;)
t.Start()
zrob_zmiana1()
t.Commit()

zrob_cos_inneg()

t2 = Transaction(doc, &quot;Zmiana 2&quot;)
t2.Start()
zrob_zmiana2()
t2.Commit()

# Scalanie dwoch transakcji
tg.Assimilate()
</code></pre>
<!-- HTML_TAG_END --></section><section id="38" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="parametry">Parametry</h2>
<pre class="language-python"><code class="language-python">import clr
--
clr.AddReference(&quot;RevitServices&quot;)
from RevitServices.Persistence import DocumentManager

clr.AddReference(&quot;RevitAPI&quot;)
from Autodesk.Revit.DB import (
  Transaction,
  UnitUtils,
  DisplayUnitType
)

doc = DocumentManager.Instance.CurrentDBDocument


wall = s0 # type: ignore
# parametr ktory jest liczba
base_offset = wall.LookupParameter(&#39;Base Offset&#39;)
base_offset.asDouble()      # 0.16404199475065617
base_offset.AsInteger()     # 0
base_offset.AsValueString() # &#39;5.00&#39;
base_offset.DisplayUnitType # Autodesk.Revit.DB.DisplayUnitType.DUT_CENTIMETERS
base_offset_cm = UnitUtils.Convert(
  base_offset.AsDouble(), 
  DisplayUnitType.DUT_DECIMAL_FEET, 
  DisplayUnitType.DUT_CENTIMETERS)   # 5.0


# parametr jako inny obiekt
base = wall.LookupParameter(&#39;Base Constraint&#39;)
base.asDouble()      # 0.0
base.AsValueString() # &#39;01-Pietro_Konstrukcja&#39;
base.AsElementId()   # &lt;Autodesk.Revit.DB.ElementId [221444]&gt;
level = doc.GetElement(base.AsElementId()) # &lt;[Autodesk.Revit.DB.Level]&gt;
level.Name # &#39;01-Pietro_Konstrukcja&#39;
level.Elevation # 9.1371391076115476
level.LookupParameter(&#39;kolejny parametr&#39;) 
# i tak dalej i tak dalej 
</code></pre>
<!-- HTML_TAG_END --></section><section id="39" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="rodzaje-parametrów">Rodzaje parametrów</h2>
<ul>
<li>String [str] <code>Nazwa Budynku</code></li>
<li>Double [float] <code>3.14</code></li>
<li>Integer [int]  <code>2345</code></li>
<li>Element - inny obiekt Revitowy (Level)</li>
<li>BuiltInParameter</li>
</ul>
<!-- HTML_TAG_END --></section><section id="40" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="parametermap">ParameterMap</h2>
<p>Jak wyciągnąć informacje o parametrach</p>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitServices&quot;)
from RevitServices.Persistence import DocumentManager

clr.AddReference(&quot;RevitAPI&quot;)
from Autodesk.Revit.DB import (
  Transaction,
  UnitUtils,
  DisplayUnitType
)

doc = DocumentManager.Instance.CurrentDBDocument


wall = s0 # type: ignore

nazwy_parametrow = [x.Definition.Name for x in wall.ParametersMap]
nazwy_parametrow_rozszerzone = [x.Definition.Name for x in wall.Parameters]
# Różnice:
#   Type
#   Family
#   Type Name
#   Category
#   Design Option
#   Family and Type
#   Type Id
#   Family Name
#   Category
</code></pre>
<p>--
    # Spotkanie 4.</p>
<!-- HTML_TAG_END --></section><section id="41" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="własna-zakładka-w-revicie">Własna zakładka w Revicie</h2>
<p><img src="/images/lectures/dh-tab.jpg" alt="dh-tab"></p>
<!-- HTML_TAG_END --></section><section id="42" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="przykład-od-większego-kolegi-z-branży">Przykład od większego kolegi z branży</h2>
<p><a href="https://youtu.be/5Pup98apob4">Webinar BIG</a></p>
<p><img src="/images/lectures/BIG-ribbon.jpg" alt="BIG-ribbon"></p>
<!-- HTML_TAG_END --></section><section id="43" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="struktura-folderów">Struktura folderów:</h2>
<img src="/images/lectures/folder.svg" alt="">

<!-- HTML_TAG_END --></section><section id="44" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="szybkie-uruchamianie">Szybkie uruchamianie</h2>
<!-- HTML_TAG_END --></section><section id="45" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h1 id="spotkanie-5">Spotkanie 5.</h1>
<!-- HTML_TAG_END --></section><section id="46" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="views">Views</h2>
<ul>
<li>View</li>
<li>FloorView</li>
<li>Viewport</li>
</ul>
<!-- HTML_TAG_END --></section><section id="47" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="viewtemplates">ViewTemplates</h2>
<!-- HTML_TAG_END --></section><section id="48" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="linked-documents">Linked documents</h2>
<pre class="language-python"><code class="language-python">lnks = FilteredElementCollector(doc).OfClass(RevitLinkInstance)
for i in lnks:
    name = i.Name.split(&quot;.rvt&quot;)[0]
    if name.endswith(&quot;IS&quot;): # Filtrujemy linki zeby znalezc wlasciwy
        doclnk = i.GetLinkDocument()
        coll = (
            FilteredElementCollector(doclnk)
            .OfCategory(BuiltInCategory.OST_GenericModel)
            .WhereElementIsNotElementType()
            .ToElements()
        )
        for x in coll:
            if x.Symbol.FamilyName.startswith(&quot;Nazwa&quot;):
                lvl = doclnk.GetElement(x.LevelId)
                lvl_name = lvl.Name
                elements.append((x, lvl_name))
    return elements

</code></pre>
<!-- HTML_TAG_END --></section><section id="49" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="wymiarowanie">Wymiarowanie</h2>
<pre class="language-python"><code class="language-python">import clr
clr.AddReference(&quot;RevitAPI&quot;)
from Autodesk.Revit.DB import (
    FilteredElementCollector,
    Transaction,
    XYZ,
    Line,
    Reference,
    ReferenceArray,
)


element, grid = selection 
p = el.GeometryCurve.GetEndPoint(0)
p_ref = el.GeometryCurve.GetEndPointReference(0)
proj = grid.Curve.Project(p)
gr_ref = Reference(grid)

# Tworzenie wymiaru
direction = grid.Curve.Direction
p1 = XYZ(p.X, p.Y, 0).Add(direction.Multiply(0.5))
p2 = proj.XYZPoint.Add(direction.Multiply(0.5))
dimline = Line.CreateBound(p1, p2) # stworzyliśmy prostopadłą
# dimline = dimline.CreateOffset(100, dimline.Direction)

refarr = ReferenceArray()
refarr.Append(p_ref)
refarr.Append(gr_ref)

t = Transaction(doc, &#39;DEV wymiar&#39;)
t.Start()
dim = doc.Create.NewDimension(doc.ActiveView, dimline, refarr)
t.Commit()
</code></pre>
<!-- HTML_TAG_END --></section><section id="50" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h1 id="spotkanie-6">Spotkanie 6.</h1>
<!-- HTML_TAG_END --></section><section id="51" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="porównywanie">Porównywanie</h2>
<h2 id="x--y">x == y</h2>
<p>Porównywanie elementów ze sobą jest proste w przypadku booleans i liczb całkowitych.
Problem zaczyna się przy zmiennoprzecinkowych <code>float</code>, czyli większości rzeczy w geometrii 3D i Revicie.</p>
<ol>
<li>Działające porównania:<ul>
<li>True == False</li>
<li>1 == 2</li>
</ul>
</li>
<li>Niedziałające np. 2.5 == 2.4 + 0.1</li>
</ol>
<p>W praktyce najczęściej 2.5 == 2.5 będzie się zgadzać i będzie dawać wynik pozytywny.
Komputer floaty zawsze trzyma w zaokrągleniu, dlatego czasem przy działaniach okazuje się, że poprawne jest takie równanie:<br>
<code>0.1 - 0.01 = 0.0900000000000000003</code></p>
<p>Dlatego najczęściej przy porównywaniu liczb zmiennoprzecinkowych lub wektorów lub punktów warto dodać tzw. epsilon.</p>
<pre class="language-python"><code class="language-python">e = 0.0001 # do jakiego zaokrąglenia ma uważać liczby za równe
x = 0.1 - 0.01
y = 0.09

if abs(x - y) &lt; e: # abs - czyli liczba bezwzględna
    return True
else:
    return False
 
</code></pre>
<!-- HTML_TAG_END --></section><section id="52" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h1 id="praca-wspólna">Praca wspólna:</h1>
<!-- HTML_TAG_END --></section><section id="53" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="narysuj-ścianę">Narysuj ścianę</h2>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitServices&quot;)
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference(&quot;RevitAPI&quot;)
from Autodesk import Revit
from Autodesk.Revit import DB, UI
from Autodesk.Revit.DB import (
    Wall,
    Document,
    Transaction
)

# uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
# doc = DocumentManager.Instance.CurrentDBDocument
uidoc = __revit__.ActiveUIDocument # type: ignore
doc = __revit__.ActiveUIDocument.Document # type: ignore

t = Transaction(doc, &#39;Create Wall&#39;)
t.Start()
try:
    Wall.Create(doc, curve, walltypeid, levelid, height, offset, flip, structural)
except:
    t.RollBack()
else:
    t.Commit()

</code></pre>
<!-- HTML_TAG_END --></section><section id="54" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="modyfikuj-parametry-ściany">Modyfikuj parametry ściany</h2>
<ul>
<li></li>
</ul>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitServices&quot;)
from RevitServices.Persistence import DocumentManager

clr.AddReference(&quot;RevitAPI&quot;)
from Autodesk.Revit.DB import (
    Transaction,
    UnitUtils,
    DisplayUnitType
)

doc = DocumentManager.Instance.CurrentDBDocument

wall = s0 # type: ignore
# parametr ktory jest liczba
base_offset = wall.LookupParameter(&#39;Base Offset&#39;)
new_offset = UnitUtils.Convert(
    15, 
    DisplayUnitType.DUT_CENTIMETERS,
    DisplayUnitType.DUT_DECIMAL_FEET)


t = Transaction(doc, &#39;Modify wall parameter&#39;)
t.Start()
try:
    # base_offset.SetValueString(&#39;15&#39;)
    base_offset.Set(new_offset)
except ValueError:
    t.RollBack()
else:
    t.Commit()

</code></pre>
<!-- HTML_TAG_END --></section><section id="55" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="zbierz-dane-ze-ścian">Zbierz dane ze ścian</h2>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitServices&quot;)
from RevitServices.Persistence import DocumentManager

clr.AddReference(&quot;RevitAPI&quot;)
from Autodesk.Revit.DB import (
    BuiltInCategory,
    FilteredElementCollector
)

doc = DocumentManager.Instance.CurrentDBDocument

# 1. jedna opcja to użyć zaznaczenia w shellu czyli &quot;selection&quot;
walls = selection # type: ignore

# 2. drugą opcją to wyfiltrowanie wszystkich ścian
walls = ( FilteredElementCollector(doc)
            .OfCategory(BuiltInCategory.OST_Walls)
            .WhereElementIsNotElementType()
            .ToElements()
)

# konterery do których zbieramy dane
powierzchnie = {}
suma = 0

# pętla przechodzaca przez każdą scianę
for wall in walls:
    typ = wall.LookupParameter(&quot;Family and Type&quot;).AsValueString()
    pow_feet = wall.LookupParameter(&quot;Area&quot;).AsDouble()
    pow_m = sq_feet_to_meter(pow_feet) 
    suma += pow_m
    if powierzchnie.get(typ):
        powierzchnie[typ] += pow_m
    else:
        powierzchnie[typ] = pow_m

# drukowanie wynikow
for typ, pow in powierzchnie.items():
    print(&#39;{}: {}m2&#39;.format(typ,pow))

print(&#39;Powierzchnia całkowita: {}m2&#39;.format(suma))

</code></pre>
<!-- HTML_TAG_END --></section><section id="56" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="wstaw-rodzinę">Wstaw rodzinę</h2>
<p>-```python
from Autodesk.Revit.DB import (
    FilteredElementCollector,
    FamilySymbol,
    BuiltInCategory,
    Structure,
    XYZ,
)</p>
<p>wszystkie_rodziny_drzwi = (FilteredElementCollector(doc)
.OfClass(typeof(FamilySymbol))
.OfCategory(BuiltInCategory.OST_Doors)
.ToElements())</p>
<p>family_symbol = wszystkie_rodziny_drzwi[0] # wybieramy pierwsza lepsza
active_view = doc.ActiveView
level = doc.GetElement(active_view.LevelId)</p>
<p>location = XYZ(0,0,0)
structural = Structure.StructuralType.NonStructural</p>
<h1 id="dla-zwykłych-rodzin">dla zwykłych rodzin</h1>
<p>nowy_obiekt = doc.Create.NewFamilyInstance(
    location = location,
    symbol = family_symbol,
    level = level,
    structuralType = structural
)</p>
<h1 id="dla-rodzin-hostowych">dla rodzin hostowych</h1>
<h1 id="doccreatenewfamilyinstance">doc.Create.NewFamilyInstance(</h1>
<h1 id="location">location,</h1>
<h1 id="symbol">symbol,</h1>
<h1 id="host--opcjonalne-dla-rodzin-z-hostami">host, # opcjonalne dla rodzin z hostami</h1>
<h1 id="level">level,</h1>
<h1 id="structuraltype">structuralType</h1>
<p>#)</p>
<h1 id="dla-rodzin-liniowych">dla rodzin liniowych</h1>
<p>#doc.Create.NewFamilyInstance(
#	location,
#	symbol,
#	host, # opcjonalne dla rodzin z hostami
#	level,
#	structuralType
#)</p>
<pre><code>

</code></pre>
<!-- HTML_TAG_END --></section><section id="57" class="svelte-1jptfcu"><!-- HTML_TAG_START --><h2 id="wymiaruj-osie">Wymiaruj osie</h2>
<pre class="language-python"><code class="language-python">import clr

clr.AddReference(&quot;RevitAPI&quot;)
from Autodesk.Revit.DB import (
    FilteredElementCollector,
    Grid,
    Transaction,
    ReferenceArray,
    Reference,
    Line,
    XYZ,
)

uidoc = __revit__.ActiveUIDocument  # type: ignore
doc = __revit__.ActiveUIDocument.Document  # type: ignore

# tutaj jest przykład, gdzie dzielę jedno sformułowanie 
# na wiele linii poprzez zamknięcie je w nawiasy
osie = ( FilteredElementCollector(doc)
    .OfClass(Grid)
    .WhereElementIsNotElementType()
    .ToElements()
)

# chcemy podzielić osie na grupy w których są one równoległe do siebie 
grupy = {}
for os in osie:
    direction = os.Curve.Direction.ToString()  # &quot;XYZ(-1,0,0)&quot;
    negate =    os.Curve.Direction.Negate().ToString() # &quot;XYZ(1,0,0)&quot;

    # będziemy używać Direction jako klucza po którym sortujemy
    if grupy.get(direction):
        grupy[direction] += [os]
    elif grupy.get(negate):
        grupy[negate] += [os]
    else:
        grupy[direction] = [os]

t = Transaction(doc, &#39;wymiarowanie osi&#39;)
t.Start()
for k, osie in grupy.items():
    if len(osie) &gt; 1:
        os1 = osie[0]
        os2 = osie[1]
        p1 = os1.Curve.GetEndPoint(0)
        p1 = XYZ(p1.X, p1.Y, 0)
        p2 = os2.Curve.Project(p1).XYZPoint

        dimline = Line.CreateBound(p1,p2)

        refarr = ReferenceArray()
        for os in osie:
            ref = Reference(os)
            refarr.Append(ref)

        dim = doc.Create.NewDimension(doc.ActiveView, dimline, refarr)
    
t.Commit()

</code></pre>
<!-- HTML_TAG_END --></section>
</main>


		<script type="module" data-sveltekit-hydrate="lf4try">
			import { start } from "../_app/immutable/start-de44d3c8.js";

			start({
				env: {},
				paths: {"base":"","assets":""},
				target: document.querySelector('[data-sveltekit-hydrate="lf4try"]').parentNode,
				version: "1679601866042",
				hydrate: {
					node_ids: [0, 9],
					data: [null,null],
					form: null
				}
			});
		</script>
	</div>
	<hr>
	<footer>
		Copyright 2023, Dawid Huczyński<br>Made with <a href="https://kit.svelte.dev/" target="_blank"
			rel="noopener noreferrer">SvelteKit</a>
	</footer>
</body>

</html>